export const siteConfig = {
  name: "FITZENIX",
  tagline: "Gym Management Software for Owners, Trainers & Members",
  description:
    "FITZENIX is gym management software for Indian gym owners — manage members, QR attendance, memberships, payments, trainers and reports with Owner, Trainer and Member apps on fitzenix.app.",
  url: "https://fitzenix.app",
  locale: "en_IN",
  language: "en-IN",
  supportEmail: "support@fitzenix.app",
  contactEmail: "hello@fitzenix.app",
  address: {
    locality: "Guindy",
    city: "Chennai",
    postalCode: "600032",
    region: "Tamil Nadu",
    country: "India",
    line: "Guindy, Chennai, Tamil Nadu 600032, India",
  },
  loginUrl: process.env.NEXT_PUBLIC_LOGIN_URL ?? "/login",
  appDownloadUrl: process.env.NEXT_PUBLIC_APP_DOWNLOAD_URL ?? "#download",
  continueUrl: process.env.NEXT_PUBLIC_APP_CONTINUE_URL ?? "#",
  startingPrice: 499,
  googleSiteVerification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION ?? "",
  socialProfiles: [
    process.env.NEXT_PUBLIC_SOCIAL_INSTAGRAM,
    process.env.NEXT_PUBLIC_SOCIAL_YOUTUBE,
    process.env.NEXT_PUBLIC_SOCIAL_LINKEDIN,
    process.env.NEXT_PUBLIC_GOOGLE_BUSINESS_PROFILE,
  ].filter((url): url is string => Boolean(url)),
} as const;
